name: industrial_watch
description: An AI based monitoring system.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider:
  multiselect: ^0.1.0
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  flutter_svg: ^2.0.7
  image_picker:
  syncfusion_flutter_gauges: ^24.2.4
  shared_preferences:
  lottie: ^3.0.0
  flutter_custom_month_picker: ^0.1.3
  dio:
  flutter_multi_formatter: ^2.12.4
  path_provider: ^2.0.2
  http:
  permission_handler:
  flutter_local_notifications:
  flutter_foreground_service: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/navbar_icons/
    - assets/icons/rank/
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
